[package]
name = "virtio_sys"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
base = { path = "../base" }
data_model = { path = "../common/data_model" }
zerocopy = { version = "0.7", features = ["derive"] }
