[package]
name = "x86_64"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
gdb = ["gdbstub_arch", "arch/gdb"]
seccomp_trace = []
swap = ["swap/enable"]

[dependencies]
acpi_tables = {path = "../acpi_tables" }
arch = { path = "../arch" }
anyhow = "*"
cfg-if = "1.0.0"
chrono = "0.4.19"
cros_fdt = { path = "../cros_fdt" }
devices = { path = "../devices" }
gdbstub_arch = { version = "0.3.0", optional = true }
hypervisor = { path = "../hypervisor" }
jail = { path = "../jail" }
kernel_cmdline = { path = "../kernel_cmdline" }
kernel_loader = { path = "../kernel_loader" }
libc = "*"
memoffset = "0.6"
once_cell = "1.7.2"
rand = "0.8"
remain = "*"
resources = { path = "../resources" }
sync = { path = "../common/sync" }
thiserror = "*"
uuid = { version = "1", features = ["v4"] }
base = { path = "../base" }
swap = { path = "../swap" }
vm_control = { path = "../vm_control" }
vm_memory = { path = "../vm_memory" }
zerocopy = { version = "0.7", features = ["derive"] }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
minijail = "*"
