[package]
name = "swap"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

# The process tests will use fork, which requires a custom test harness to enforce single threaded
# execution.
[[test]]
name = "main"
path = "tests/main.rs"
harness = false


[features]
trace_marker = ["cros_tracing/trace_marker"]
log_page_fault = []
enable = ["userfaultfd", "userfaultfd-sys"]

[dependencies]
anyhow = "*"
base = { path = "../base" }
cfg-if = "*"
cros_tracing = { path = "../cros_tracing" }
data_model = { path = "../common/data_model" }
jail = { path = "../jail" }
num_cpus = "*"
once_cell = "*"
remain = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "*"
sync = { path = "../common/sync" }               # provided by ebuild
thiserror = "*"
vm_memory = { path = "../vm_memory" }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
libc = "*"

[target.'cfg(target_os="linux")'.dependencies]
userfaultfd = { version = "0.7.0", optional = true }
userfaultfd-sys = { version = "0.5.0", optional = true }

[dev_dependencies]
libtest-mimic = "0.6"
tempfile = "*"
