[package]
name = "jail"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
seccomp_trace = []

[dependencies]
anyhow = "*"
base = { path = "../base" }
libc = "*"
once_cell = "*"
serde = "*"
serde_keyvalue = { path = "../serde_keyvalue", features = ["argh_derive"] }
static_assertions = "*"
zerocopy = { version = "0.7", features = ["derive"] }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
minijail = "*"

[build-dependencies]
which = "4"
rayon = "1.5.3"

[dev-dependencies]
cfg-if = "*"
