[package]
name = "vm_memory"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
anyhow = "1.0.32"
cfg-if = "1.0.0"
cros_async = { path = "../cros_async" }
data_model = { path = "../common/data_model" }
libc = "*"
base = { path = "../base" }
bitflags = "2.2.1"
remain = "*"
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"
thiserror = "*"
zerocopy = { version = "0.7", features = ["derive"] }
